defaultContentLanguage: lt
pagination:
  pagerSize: 6
menu:
  main:
    - name: Kubernetes
      url: '/paslauga/kubernetes/'
      weight: 1
    - name: n8n
      url: '/paslauga/n8n/'
      weight: 2
    - name: DevOps
      url: '/paslauga/devops/'
      weight: 3
    - name: SOC 2
      url: '/paslauga/soc2/'
      weight: 4
  sitemap:
    - name: Pradžia
      url: '/'
      weight: 1
    - name: Kubernetes
      url: '/paslauga/kubernetes/'
      weight: 2
    - name: DevOps
      url: '/paslauga/devops/'
      weight: 3
    - name: n8n
      url: '/paslauga/n8n/'
      weight: 4
    - name: SOC 2
      url: '/paslauga/soc2/'
      weight: 5
    - name: Pasikalbėkime
      url: '/pasikalbekime/'
      weight: 6
    - name: Privatumo politika
      url: '/teisinis/privatumo-politika/'
      weight: 7
params:
  logo: /images/logo.webp
  address:
    phone: +370 612 30123
    email: labas@k8s.lt
    openingHours: 9.00 - 18.00 darbo dienomis
disableHugoGeneratorInject: true
disableGeneratorVersion: false
taxonomies:
  category: categories
  tag: tags
disableKinds:
  - taxonomy
  - term
enableRobotsTXT: true
minify:
  minifyOutput: true
sitemap:
  changeFreq: "0.9"
  filename: sitemap.xml
  priority: 1

markup:
  goldmark:
    renderer:
      unsafe: true